sonar.projectKey=Strifere_PurePrompt
sonar.organization=pureprompt1
sonar.sources=pure-prompt
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/tests/**,**/prisma/migrations/**,**/ui/carbon-badge.tsx,**/ui/fonts.ts

sonar.javascript.lcov.reportPaths=pure-prompt/coverage/lcov.info