sonar.projectKey=Strifere_GreenPrompt-Guide
sonar.organization=greenprompt-guide
sonar.sources=greenprompt-guide
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/tests/**,**/prisma/migrations/**,**/ui/carbon-badge.tsx,**/ui/fonts.ts

sonar.javascript.lcov.reportPaths=greenprompt-guide/coverage/lcov.info