import type { Metadata } from "next";
import Link from "next/link";
import { montserrat } from "./ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="topbar">
          <div className="brand">PurePrompt</div>
          <nav className="topnav-links" aria-label="Primary">
            <Link href="/catalog">Catalog</Link>
            <Link href="/contribute">Contribute</Link>
            <Link href="/">About</Link>
          </nav>
          <div className="topbar-cta">
            <Link href="/login" className="ghost-btn">
              Log in
            </Link>
            <Link href="/contribute" className="solid-btn">
              Sign up
            </Link>
          </div>
        </header>
        <main className="app-main">{children}</main>
      </body>
    </html>
  );
}
