
export const TOOLTIPS = {
  // Catalog filters
  SEARCH_BOX: "Search by practice name or description.",
  FILTER_CATEGORIES: "Filter practices by thematic category (e.g. Prompt Design, Inference).",
  FILTER_MODELS: "Filter by the AI model used in the source study.",
  FILTER_PROMPT_TECHNIQUES: "Filter by the prompt technique used in the practice or source study.",
  FILTER_DATASETS: "Filter by the dataset used in the source study.",
  FILTER_HYPERPARAMETERS: "Filter by the hyperparameter used in the practice or the source study.",
  PRACTICE_METRICS: "Metrics are indicators that were extracted from the source the practice comes from. They serve as quantitative measures of the models' performance when the practice is applied on the prompts they process.",
  PRACTICE_GREEN_SCORE: "The Green Score is a metric specific to the GreenPrompt Guide, ranging from 0 to 100. It quantifies the 'greenness' of a prompt engineering practice, representing its potential to reduce computational resources, token usage, and overall environmental impact when applied.",
  PRACTICE_ORIGINAL_PROMPT: "The original prompt is the initial version of the prompt that was used before any changes that the practice describes were made. It serves as a baseline for comparison with the improved prompt.",
  PRACTICE_IMPROVED_PROMPT: "The improved prompt is the revised version of the original prompt with the practice applied, designed to enhance performance or reduce environmental impact.",
  PRACTICE_PROMPT_TECHNIQUES: "The prompt techniques used in the practice or the source study. A Prompt Technique is a specific, repeatable strategy or method for structuring a prompt to achieve a desired outcome.",
  PRACTICE_MODELS: "The AI model used in the source study from which the practice was extracted.",
  PRACTICE_HYPERPARAMETERS: "Hyperparameters used in the practice or the source study. They are external configuration settings that are defined before running a Language Model. They are not learned from the data but are set by the user to control the model's behavior.",
  PRACTICE_DATASETS: "The dataset used in the source study from which the practice was extracted. Datasets are a compilation of data used for training or testing the AI models used on the studies where the practice was extracted.",
  REFERENCE_PROMPT_TECHNIQUES: "The prompt techniques used in the source study. A Prompt Technique is a specific, repeatable strategy or method for structuring a prompt to achieve a desired outcome.",
  REFERENCE_MODELS: "The AI model used in the source study.",
  REFERENCE_HYPERPARAMETERS: "Hyperparameters used in the source study. They are external configuration settings that are defined before running a Language Model. They are not learned from the data but are set by the user to control the model's behavior.",
  REFERENCE_DATASETS: "The datasets used in the source study. Datasets are a compilation of data used for training or testing the AI models used on the study in order to conduct the experiments they define.",
  REFERENCE_CITATION: "In IEEE format, the citation of the source study from which the practice was extracted.",
  DATASET_SIZE: "The size of the dataset, if specified. This can refer to the number of samples, records, or data points contained within the dataset, and a data measure type like bytes as well.",
  DATASET_DATA_FORMAT_TYPES: "The data format types are the strcutures or formats in which the data is organized within the dataset. Examples include CSV, JSON, XML, and Parquet. The data format types can affect how the data is processed and utilized in AI models.",
  MODEL_DATA_FORMAT_TYPES: "The data format types are the strcutures or formats in which the data that the model can process and interpret is organized.",
  HYPERPARAMETERS_SYNTAX: "The syntax of the hyperparameter, which includes its name and value. It's an example on how the hyperparameter can be set on the model configuration.",
  HYPERPARAMETERS_DATA_TYPE: "The data type of the hyperparameter, which indicates the kind of value it can accept. Common data types include string, integer (int), float and boolean (bool).",
  MODEL_PARAMETERS: "The number of parameters in the model, which refers to the total count of learnable weights and biases that the model uses to make predictions. A higher number of parameters can indicate a more complex model with greater capacity to learn from data, but it may also require more computational resources and data to train effectively.",
  MODEL_SIZE: "The size of the model, which can refer to the amount of memory or storage space required to store the model's parameters and architecture. It can also indicate the complexity of the model, with larger models often having more parameters and potentially greater capacity for learning and generalization.",
} as const;